---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.6.1
  amd64: ghcr.io/hassio-addons/debian-base:7.6.1
  armhf: ghcr.io/hassio-addons/debian-base:7.6.1
  armv7: ghcr.io/hassio-addons/debian-base:7.6.1
  i386: ghcr.io/hassio-addons/debian-base:7.6.1
